config/routes.rb
Rails.application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :admins, skip: :registrations
  resources :posts

  get 'home/index'
  get '*path' => redirect("/")

  root "home#index"
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/redactor_rails/asset.rb
class RedactorRails::Asset < ActiveRecord::Base
  include RedactorRails::Orm::ActiveRecord::AssetBase
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  validates_presence_of :data
end

app/models/redactor_rails/document.rb
class RedactorRails::Document < RedactorRails::Asset
  mount_uploader :data, RedactorRailsDocumentUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end

  def as_json_methods
    [:image]
  end
end

app/models/redactor_rails/picture.rb
class RedactorRails::Picture < RedactorRails::Asset
  mount_uploader :data, RedactorRailsPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_technical_level

  def set_technical_level
    cookies[:technical_level] = "Intermediate" if cookies[:technical_level].blank?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @page_description = "A highly skilled software engineer working with Ruby on Rails, Java and C#, writing about software development and 3D graphics."
    render layout: 'homepage', text: ""
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @posts = Post.all
    @page_title       = 'Posts'
    @page_description = 'Short writings and notes about software development from Matt Ryder'
    @page_keywords    = 'Matt Ryder, Software, Rails, Ruby, Java, gamedev, Development'
  end

  def show
    @page_title       = @post.title
    @page_description = @post.summary
    counts = @post.article.split(" ").each_with_object(Hash.new(0)) { |e, h| h[e] += 1 }
    counts = counts.sort_by{|k,v| v}.reverse.first(10).map{|k,v| k} if counts.present?

    @page_keywords    = 'Matt Ryder, Software, Rails, Ruby, ' + counts.join(", ")
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(project_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(project_params)
        format.html { redirect_to @post, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:post).permit(:title, :article, :summary, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.haml
!!!
%html{lang: 'en'}
  %head
    = display_meta_tags :site => 'Matt Ryder, Ruby on Rails Developer', :title => 'Hello', :reverse => true
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{name: 'viewport', content: "width=device-width", "initial-scale" => 1}
  %body{class: "#{'body-intro' if current_page?(root_path)}" }
    %nav.navbar
      .container-fluid
        .center-container
          .navbar-header
            %button.navbar-toggle.collapsed{"data-target" => "#navibar", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{ href: root_path }
              Matt Ryder

          #navibar.collapse.navbar-collapse
            %ul.nav.navbar-nav.navbar-right
              %li
                = link_to "Posts", posts_path
              %li
                = link_to  "Github", "https://github.com/MattRyder"
              %li
                = link_to "LinkedIn", "https://uk.linkedin.com/pub/matt-ryder/a7/a2/668/"
              %li
                = link_to "Twitter", "https://twitter.com/CSMattRyder"

  - if notice.present?
    .notice= notice
  - if alert.present?
    .alert= alert

  .center-container
    = yield

app/views/layouts/homepage.html.haml
!!!
%html{lang: 'en'}
  %head
    = display_meta_tags :site => 'Matt Ryder, Ruby on Rails Developer', :title => 'Hello', :reverse => true
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{name: 'viewport', content: "width=device-width", "initial-scale" => 1}
  %body
    .body-intro
      #intro
        .text
          %h2 Matt Ryder
          %h3 Ruby on Rails Developer

      %nav.navbar
        .container-fluid
          .navbar-header
            %button.navbar-toggle.collapsed{"data-target" => "#navibar", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar

          #navibar.collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li
                = link_to "Posts", posts_path
              %li
                = link_to  "Github", "https://github.com/MattRyder"
              %li
                = link_to "LinkedIn", "https://uk.linkedin.com/pub/matt-ryder/a7/a2/668/"
              %li
                = link_to "Twitter", "https://twitter.com/CSMattRyder"

#intro-content
  .alpha
    %section
      %h3 Not all software is created equal
      %p I'm a pure software engineer, from requirements analysis through to implementation, anything less than 100% is an affront to the client.

    %section
      %h3 Including and not limited to...
      %p Software development is a huge part of who I am, so I invest a lot of time working with as many languages and tools as I can.
      %p I have professional experience with Ruby and C#; far too much knowledge of Java, PHP and Javascript; and I'm branching out into C++ and Rust.
      %p All of the products I build with these eventually make their way onto Github, so check that out to find what I'm currently playing about with.

    .cee-tee-ay
      %section
        %span If you think I can help you, please
        = mail_to "matt@mattryder.co.uk", "drop me a line!"

app/views/posts/_form.html.haml
= simple_form_for @post, class: "form-horizontal" do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  = f.input :title
  = f.input :article, input_html: {class: "redactor"}
  = f.input :summary
  = f.input :category
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
.col-xs-10.col-xs-offset-1
  %h1 Editing post

  = render 'form'

  = link_to 'Show', @post
  \|
  = link_to 'Back', posts_path

app/views/posts/index.html.haml
%h2.post-heading Posts

- @posts.each do |post|
  .post
    %h2= link_to post.title, post
    %p= post.summary


- if admin_signed_in?
  = link_to 'New Post', new_post_path

app/views/posts/new.html.haml
.col-xs-10.col-xs-offset-1
  %h1 Create New Post

  = render 'form'

  = link_to 'Back', posts_path

app/views/posts/show.html.haml
.post-show
  %h1= link_to @post.title, @post
  %h4.summary= @post.summary

  %article
    = @post.article.html_safe

  .cee-tee-ay
    %section
      %span That's just the start, really. To keep up to date on this,
      = link_to "follow @CSMattRyder on Twitter", "https://twitter.com/CSMattRyder"